import statistics
"""

                                            ###|||Averages and measures of central location|||###
                                ###|||These functions calculate an average or typical value from a population or sample.|||###

(1)mean()= Arithmetic mean (“average”) of data.

(2)fmean()= Fast, floating-point arithmetic mean, with optional weighting.

(3)geometric_mean()= Geometric mean of data.

(4)harmonic_mean()= Harmonic mean of data.

(5)kde()= Estimate the probability density distribution of the data.

(5)kde_random()= Random sampling from the PDF generated by kde().

(6)median()= Median (middle value) of data.

(7)median_low()= Low median of data.

(8)median_high()= High median of data.

(9)median_grouped()= Median (50th percentile) of grouped data.

(10)mode()= Single mode (most common value) of discrete or nominal data.

(11)multimode()= List of modes (most common values) of discrete or nominal data.

(12)quantiles()= Divide data into intervals with equal probability.

                                        ####|||| Measures of spread |||###
        ###||| These functions calculate a measure of how much the population or sample tends to deviate from the typical or average values.|||###

(13)pstdev()= Population standard deviation of data.

(14)pvariance()= Population variance of data.

(15)stdev()= Sample standard deviation of data.

(16)variance()= Sample variance of data.

                                            ###||| Statistics for relations between two inputs |||###  
                            ###||| These functions calculate statistics regarding relations between two inputs.|||###

(17)covariance()= Sample covariance for two variables.

(18)correlation()= Pearson and Spearman’s correlation coefficients.

(19)linear_regression()= Slope and intercept for simple linear regression.


    """
    
    

number=[1,2,3,4,5,7,8,9,6,1]
mean_value=statistics.mean(number)
print(mean_value)
